Allow more than one table

diff --git a/user/files/flush-table b/user/files/flush-table
--- a/user/files/flush-table
+++ b/user/files/flush-table
@@ -2,11 +2,13 @@
 set -e -o pipefail
 if test "$(id -u)" -eq 0; then
 	if test -z "${1:-}"; then
-		echo "error: please specify a table:" >&2
+		echo "error: please specify at least one table:" >&2
 		pfctl -s Tables >&2
 		exit 2
 	fi
-	pfctl -t "$1" -T flush
+	for table in "$@"; do
+		pfctl -t "$table" -T flush
+	done
 else
 	echo Switching to root...
 	exec sudo $0 "$@"
